project_id = "tdfyccorqobrkymoiuit"

[functions.search-generator]
verify_jwt = false

[functions.hotels-search]
verify_jwt = false

[functions.verify-gender]
verify_jwt = false

[functions.parental-location]
verify_jwt = false

[functions.parental-sos]
verify_jwt = false

[functions.parental-trip-update]
verify_jwt = false

[functions.chatbot]
verify_jwt = false

[functions.ai-hotel-search]
verify_jwt = false

[functions.generate-cover-image]
verify_jwt = false
